version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps-yarn)'
    groups:
      security-version-updates:
        applies-to: security-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      dep-version-updates:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'patch'
    ignore:
      # For all deps - ignore all major updates
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 2
    labels:
      - ':robot: Dependabot'
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps-gh-actions)'
    open-pull-requests-limit: 1
    labels:
      - ':robot: Dependabot'
  - package-ecosystem: 'docker'
    directories:
      - '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps-docker)'
    open-pull-requests-limit: 1
    labels:
      - ':robot: Dependabot'
  - package-ecosystem: 'pip'
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps-pip)'
    groups:
      security-version-updates:
        applies-to: security-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      dep-version-updates:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 2
    labels:
      - ':robot: Dependabot'
